### ISSUE TITLE
Task search JSON fixtures are out of date

### ISSUE THREAD

**Issue by mbernst** [crowdresearch/crowdsource-platform#151]
This is in the readme: `python manage.py loaddata fixtures/neilTaskRankingData.json`

But results in:
Traceback (most recent call last):
	  File "manage.py", line 10, in <module>
	    execute_from_command_line(sys.argv)
	  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
	    utility.execute()
	  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 330, in execute
	    self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
	    self.execute(*args, **cmd_options)
	  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 441, in execute
	    output = self.handle(*args, **options)
	  File "/Library/Python/2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
	    self.loaddata(fixture_labels)
	  File "/Library/Python/2.7/site-packages/django/core/management/commands/loaddata.py", line 96, in loaddata
	    connection.check_constraints(table_names=table_names)
	  File "/Library/Python/2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 221, in check_constraints
	    self.cursor().execute('SET CONSTRAINTS ALL IMMEDIATE')
	  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 79, in execute
	    return super(CursorDebugWrapper, self).execute(sql, params)
	  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 64, in execute
	    return self.cursor.execute(sql, params)
	  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 97, in __exit__
	    six.reraise(dj_exc_type, dj_exc_value, traceback)
	  File "/Library/Python/2.7/site-packages/django/db/backends/utils.py", line 62, in execute
	    return self.cursor.execute(sql)
	django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "crowdsourcing_userprofile" violates foreign key constraint "crowdsourcing_userprof_user_id_7592ae1f4a72d702_fk_auth_user_id"
	DETAIL:  Key (user_id)=(2) is not present in table "auth_user".

Did something change about the model?

**Comment by dmorina** [comment]
No, just the json file needs to be adjusted

**Comment by ryosuzuki** [comment]
+1

**Comment by neilthemathguy** [comment]
**The updated file should runs perfectly fine** 
`manage.py loaddata fixtures/neilTaskRankingData.json`
Installed 942 object(s) from 1 fixture(s)

**In case you want to add requester  add below. Otherwise use the updated file** 

``` JSON 
    {
        "fields": {
            "profile":2
        },
        "model": "crowdsourcing.requester",
        "pk": 2
    },
     {
        "fields": {
            "profile":3
        },
        "model": "crowdsourcing.requester",
        "pk": 3
    } 
```
