### ISSUE TITLE
Missing bower dependencies 

### ISSUE THREAD

**Issue by ryosuzuki** [crowdresearch/crowdsource-platform#245]
Application seems crash due to missing bower components.

```
GET http://localhost:8000/static/bower_components/query-string/query-string.js 
localhost/:151 GET http://localhost:8000/static/bower_components/angular-oauth2/dist/angular-oauth2.js 404 (NOT FOUND)
angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module crowdsource due to:
Error: [$injector:modulerr] Failed to instantiate module angular-oauth2 due to:
Error: [$injector:nomod] Module 'angular-oauth2' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.14/$injector/nomod?p0=angular-oauth2
    at REGEX_STRING_REGEXP (http://localhost:8000/static/bower_components/angular/angular.js:63:12)
    at http://localhost:8000/static/bower_components/angular/angular.js:1767:17
    at ensure (http://localhost:8000/static/bower_components/angular/angular.js:1691:38)
    at module (http://localhost:8000/static/bower_components/angular/angular.js:1765:14)
    at http://localhost:8000/static/bower_components/angular/angular.js:4097:22
    at forEach (http://localhost:8000/static/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:8000/static/bower_components/angular/angular.js:4081:5)
    at http://localhost:8000/static/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost:8000/static/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:8000/static/bower_components/angular/angular.js:4081:5)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=angular-oauth2&p1=…lhost%3A8000%2Fstatic%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)
    at REGEX_STRING_REGEXP (http://localhost:8000/static/bower_components/angular/angular.js:63:12)
    at http://localhost:8000/static/bower_components/angular/angular.js:4120:15
    at forEach (http://localhost:8000/static/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:8000/static/bower_components/angular/angular.js:4081:5)
    at http://localhost:8000/static/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost:8000/static/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:8000/static/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost:8000/static/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://localhost:8000/static/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://localhost:8000/static/bower_components/angular/angular.js:1466:12)
http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=crowdsource&p1=Err…host%3A8000%2Fstatic%2Fbower_components%2Fangular%2Fangular.js%3A1466%3A12)REGEX_STRING_REGEXP @ angular.js:63(anonymous function) @ angular.js:4120forEach @ angular.js:323loadModules @ angular.js:4081createInjector @ angular.js:4007doBootstrap @ angular.js:1445bootstrap @ angular.js:1466angularInit @ angular.js:1360(anonymous function) @ angular.js:26176jQuery.Callbacks.fire @ jquery.js:1037jQuery.Callbacks.self.fireWith @ jquery.js:1148jQuery.extend.ready @ jquery.js:433completed @ jquery.js:103
```

**Comment by ryosuzuki** [comment]
Related commit: 252793df818e76ad92a4805ec5416b98ec1cad19

**Comment by ryosuzuki** [comment]
```
bower install
```

**Comment by dmorina** [comment]
we have upgraded to angular 1.4.0 remove your bower components(optional) and do a clean install

**Comment by ryosuzuki** [comment]
Resolved.
