### ISSUE TITLE
Check data source exists before trying to read it

### ISSUE THREAD

**Issue by nistala** [crowdresearch/crowdsource-platform#474]
NPE Doesn't impact functionality but shows an error in the console.

Go task design, don't upload csv and click on autocomplete data source box.

TypeError: Cannot read property 'column_headers' of undefined
    at ProjectController.self.querySearch (http://localhost:8000/static/js/project/controllers/project.controller.js:39:71)
    at fn (eval at <anonymous> (http://localhost:8000/static/bower_components/angular/angular.js:13036:15), <anonymous>:4:385)
    at Scope.$get.Scope.$eval (http://localhost:8000/static/bower_components/angular/angular.js:15719:28)
    at W (http://localhost:8000/static/bower_components/angular-material/angular-material.min.js:11:8242)
    at Q (http://localhost:8000/static/bower_components/angular-material/angular-material.min.js:11:9004)
    at http://localhost:8000/static/bower_components/angular-material/angular-material.min.js:11:6360
    at processQueue (http://localhost:8000/static/bower_components/angular/angular.js:14454:28)
    at http://localhost:8000/static/bower_components/angular/angular.js:14470:27
    at Scope.$get.Scope.$eval (http://localhost:8000/static/bower_components/angular/angular.js:15719:28)
    at Scope.$get.Scope.$digest (http://localhost:8000/static/bower_components/angular/angular.js:15530:31)

**Comment by shirishgoyal** [comment]
Resolved in https://github.com/crowdresearch/crowdsource-platform/pull/478
